use WebShopDb
go

insert Category ([DisplayName], [Link]) values ('Eletronic', 'eletronic') -- id 1
insert Category ([DisplayName], [Link]) values ('Audio / video', 'audio_video') -- id 2
go

insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Prebuild computers', 'prebuild_computers', 1)		-- id 1
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Computers components', 'computers_components', 1)	-- id 2
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Sreens', 'screens', 1)							-- id 3
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Storage', 'storage', 1)							-- id 4
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Microfons', 'microfons', 2)						-- id 5
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Dslr', 'dslr', 2)									-- id 6
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Mirrorless cameras', 'mirrorless_cameras', 2)		-- id 7
insert Subcategory ([DisplayName], [Link], [CategoryId]) values ('Analog cameras', 'analog_cameras', 2)				-- id 8
go

insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title1', 'Description 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8221', 15.99, 1)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title2', 'Description 2 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8206', 15.99, 1)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title3', 'Description 3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8202', 15.99, 2)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title4', 'Description 4 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8201', 15.99, 2)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title4', 'Description 5 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8221', 15.99, 3)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title5', 'Description 6 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8206', 15.99, 3)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title6', 'Description 7 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8202', 15.99, 4)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title7', 'Description 8 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8201', 15.99, 4)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title8', 'Description 9 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8221', 15.99, 5)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title9', 'Description 10 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8206', 15.99, 5)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title10', 'Description 11 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8202', 15.99, 6)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title11', 'Description 12 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8201', 15.99, 6)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title12', 'Description 13 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8221', 15.99, 7)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title13', 'Description 14 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8206', 15.99, 7)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title14', 'Description 15 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8202', 15.99, 8)
insert Product ([Title], [Description], [ImageName], [Price], [SubcategoryId]) values ('Title15', 'Description 16 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero diam, pellentesque sed vehicula in, laoreet nec sapien. Curabitur dapibus mauris libero, sed facilisis purus aliquet condimentum. Integer ultrices metus venenatis, interdum enim id, ultricies magna. Nunc enim leo, tristique sit amet nulla et, facilisis molestie ex. Pellentesque sollicitudin enim sed mi malesuada dapibus. Duis nec urna faucibus nulla elementum gravida non sit amet nunc. Nam varius quam eget quam luctus lobortis.', 'IMG_8201', 15.99, 8)
go

insert Roles ([RoleName]) values ('CUSTOMER')
insert Roles ([RoleName]) values ('ADMIN')
go

insert Users ([FirstName], [LastName], [Email], [Password], [RoleId]) values ('Pero', 'Peric', 'pero.peric@gmail.com', 'test123', 2)
insert Users ([FirstName], [LastName], [Email], [Password], [RoleId]) values ('Ivan', 'Ivic', 'ivan.ivic@gmail.com', 'test123', 1)
insert Users ([FirstName], [LastName], [Email], [Password], [RoleId]) values ('Iva', 'Ivic', 'iva.ivic@gmail.com', 'test123', 1)
insert Users ([FirstName], [LastName], [Email], [Password], [RoleId]) values ('Lea', 'Leic', 'lea.leic@gmail.com', 'test123', 1)
go