version: "3.9"
services:
  web-shop:
    image: "josipsh/web-shop"
    ports:
      - "8092:8080"
    depends_on:
      - blob-storage
      - mssql

  blob-storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "20000:10000"

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1434:1433"
    environment:
      - MSSQL_SA_PASSWORD=MySecretPassword
      - ACCEPT_EULA=Y
